// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package lineitems

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Line items related queries
	CreateLineItem(ctx context.Context, arg CreateLineItemParams) (LineItem, error)
	DeleteLineItem(ctx context.Context, id int32) error
	GetLineItem(ctx context.Context, id int32) (LineItem, error)
	GetLineItemsByBill(ctx context.Context, billID pgtype.Int4) ([]LineItem, error)
	GetTotalAmountByBill(ctx context.Context, billID pgtype.Int4) (interface{}, error)
	UpdateLineItem(ctx context.Context, arg UpdateLineItemParams) (LineItem, error)
}

var _ Querier = (*Queries)(nil)
