// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: currencies.sql

package currencies

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrency = `-- name: GetCurrency :one

SELECT id, code, symbol, rate, enabled FROM currencies WHERE code = $1 AND enabled = true
`

// Currencies related queries
func (q *Queries) GetCurrency(ctx context.Context, code pgtype.Text) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrency, code)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Symbol,
		&i.Rate,
		&i.Enabled,
	)
	return i, err
}
