// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package currencies

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Currencies related queries
	GetCurrency(ctx context.Context, code pgtype.Text) (Currency, error)
}

var _ Querier = (*Queries)(nil)
