// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package lineitems

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bill struct {
	ID               int32
	Currency         string
	Status           string
	CloseReason      pgtype.Text
	ErrorMessage     pgtype.Text
	TotalAmountCents pgtype.Int8
	StartTime        pgtype.Timestamptz
	EndTime          pgtype.Timestamptz
	BilledAt         pgtype.Timestamptz
	IdempotencyKey   string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Currency struct {
	ID      int32
	Code    pgtype.Text
	Symbol  pgtype.Text
	Rate    pgtype.Numeric
	Enabled bool
}

type LineItem struct {
	ID             int32
	BillID         pgtype.Int4
	AmountCents    int64
	Currency       string
	Description    pgtype.Text
	IncurredAt     pgtype.Timestamptz
	ReferenceID    pgtype.Text
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Metadata       []byte
}
