// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bills.sql

package bills

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBill = `-- name: CreateBill :one

INSERT INTO bills (
    currency,
    status,
    start_time,
    end_time,
    idempotency_key
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, currency, status, close_reason, error_message, total_amount_cents, start_time, end_time, billed_at, idempotency_key, created_at, updated_at
`

type CreateBillParams struct {
	Currency       string
	Status         string
	StartTime      pgtype.Timestamptz
	EndTime        pgtype.Timestamptz
	IdempotencyKey string
}

// Bills related queries
func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.Currency,
		arg.Status,
		arg.StartTime,
		arg.EndTime,
		arg.IdempotencyKey,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Status,
		&i.CloseReason,
		&i.ErrorMessage,
		&i.TotalAmountCents,
		&i.StartTime,
		&i.EndTime,
		&i.BilledAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBill = `-- name: GetBill :one
SELECT id, currency, status, close_reason, error_message, total_amount_cents, start_time, end_time, billed_at, idempotency_key, created_at, updated_at FROM bills WHERE id = $1
`

func (q *Queries) GetBill(ctx context.Context, id int32) (Bill, error) {
	row := q.db.QueryRow(ctx, getBill, id)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Status,
		&i.CloseReason,
		&i.ErrorMessage,
		&i.TotalAmountCents,
		&i.StartTime,
		&i.EndTime,
		&i.BilledAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillByIdempotencyKey = `-- name: GetBillByIdempotencyKey :one
SELECT id, currency, status, close_reason, error_message, total_amount_cents, start_time, end_time, billed_at, idempotency_key, created_at, updated_at FROM bills WHERE idempotency_key = $1
`

func (q *Queries) GetBillByIdempotencyKey(ctx context.Context, idempotencyKey string) (Bill, error) {
	row := q.db.QueryRow(ctx, getBillByIdempotencyKey, idempotencyKey)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Status,
		&i.CloseReason,
		&i.ErrorMessage,
		&i.TotalAmountCents,
		&i.StartTime,
		&i.EndTime,
		&i.BilledAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillStatus = `-- name: UpdateBillStatus :one
UPDATE bills 
SET status = $2, updated_at = NOW()
WHERE id = $1 
RETURNING id, currency, status, close_reason, error_message, total_amount_cents, start_time, end_time, billed_at, idempotency_key, created_at, updated_at
`

type UpdateBillStatusParams struct {
	ID     int32
	Status string
}

func (q *Queries) UpdateBillStatus(ctx context.Context, arg UpdateBillStatusParams) (Bill, error) {
	row := q.db.QueryRow(ctx, updateBillStatus, arg.ID, arg.Status)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Status,
		&i.CloseReason,
		&i.ErrorMessage,
		&i.TotalAmountCents,
		&i.StartTime,
		&i.EndTime,
		&i.BilledAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
