// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package bills

import (
	"context"
)

type Querier interface {
	// Bills related queries
	CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error)
	GetBill(ctx context.Context, id int32) (Bill, error)
	GetBillByIdempotencyKey(ctx context.Context, idempotencyKey string) (Bill, error)
	UpdateBillStatus(ctx context.Context, arg UpdateBillStatusParams) (Bill, error)
}

var _ Querier = (*Queries)(nil)
